# Generated by Django 5.0.2 on 2024-03-07 17:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False, verbose_name='顏色ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='顏色名稱')),
            ],
            options={
                'verbose_name': '顏色',
                'verbose_name_plural': '顏色',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('total_views', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('daily_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分類ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='分類名稱')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
            },
        ),
        migrations.CreateModel(
            name='registered_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('user_sex', models.CharField(default='M', max_length=2)),
                ('password', models.CharField(max_length=128)),
                ('user_birthday', models.DateField()),
                ('user_mail', models.EmailField(blank=True, default='', max_length=100)),
                ('user_tel', models.CharField(blank=True, default='', max_length=50)),
                ('user_address', models.CharField(blank=True, default='', max_length=255)),
                ('is_blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False, verbose_name='尺寸ID')),
                ('size_name', models.CharField(max_length=50, verbose_name='尺寸名稱')),
            ],
            options={
                'verbose_name': '尺寸',
                'verbose_name_plural': '尺寸',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('product_name', models.CharField(default='', max_length=100, verbose_name='商品名稱')),
                ('price', models.IntegerField(default=0, verbose_name='價格')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品圖片')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.colormodel', verbose_name='顏色')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.producttypemodel', verbose_name='商品分類')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sizemodel', verbose_name='尺寸')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='圖片ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='圖片')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.products', verbose_name='商品')),
            ],
            options={
                'verbose_name': '圖片',
                'verbose_name_plural': '圖片',
            },
        ),
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('description_id', models.AutoField(primary_key=True, serialize=False, verbose_name='敘述ID')),
                ('description', models.TextField(verbose_name='敘述')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='myapp.products', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品敘述',
                'verbose_name_plural': '商品敘述',
            },
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField(default=0)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('customer_address', models.CharField(default='', max_length=100)),
                ('customer_phone', models.CharField(default='', max_length=100)),
                ('shipping_method', models.CharField(default='', max_length=50)),
                ('pay_type', models.CharField(default='', max_length=50)),
                ('customer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.registered_user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorSizeStockModel',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_size_stocks', to='myapp.colormodel', verbose_name='顏色ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_size_stocks', to='myapp.products', verbose_name='商品ID')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_size_stocks', to='myapp.sizemodel', verbose_name='尺寸ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colormodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordersmodel')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sizemodel')),
            ],
        ),
    ]
