# Generated by Django 4.2.7 on 2024-02-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registered_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Usersex', models.CharField(default='M', max_length=2)),
                ('Passwd', models.CharField(max_length=128)),
                ('Userbirthday', models.DateField()),
                ('Usermail', models.EmailField(blank=True, default='', max_length=100)),
                ('Usertel', models.CharField(blank=True, default='', max_length=50)),
                ('Useraddress', models.CharField(blank=True, default='', max_length=255)),
                ('Isblacklisted', models.BooleanField(default=False)),
            ],
        ),
    ]
