# Generated by Django 5.0.2 on 2024-03-07 07:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('ColorID', models.AutoField(primary_key=True, serialize=False, verbose_name='顏色ID')),
                ('ColorName', models.CharField(max_length=50, verbose_name='顏色名稱')),
            ],
            options={
                'verbose_name': '顏色',
                'verbose_name_plural': '顏色',
            },
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grandtotal', models.IntegerField(default=0)),
                ('customname', models.CharField(default='', max_length=100)),
                ('customaddress', models.CharField(default='', max_length=100)),
                ('customphone', models.CharField(default='', max_length=100)),
                ('shipping_method', models.CharField(default='', max_length=50)),
                ('paytype', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('total_views', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('daily_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False, verbose_name='分類ID')),
                ('TypeName', models.CharField(max_length=50, verbose_name='分類名稱')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
            },
        ),
        migrations.CreateModel(
            name='registered_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Usersex', models.CharField(default='M', max_length=2)),
                ('Passwd', models.CharField(max_length=128)),
                ('Userbirthday', models.DateField()),
                ('Usermail', models.EmailField(blank=True, default='', max_length=100)),
                ('Usertel', models.CharField(blank=True, default='', max_length=50)),
                ('Useraddress', models.CharField(blank=True, default='', max_length=255)),
                ('Isblacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('SizeID', models.AutoField(primary_key=True, serialize=False, verbose_name='尺寸ID')),
                ('SizeName', models.CharField(max_length=50, verbose_name='尺寸名稱')),
            ],
            options={
                'verbose_name': '尺寸',
                'verbose_name_plural': '尺寸',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('ProductName', models.CharField(default='', max_length=100, verbose_name='商品名稱')),
                ('Price', models.IntegerField(default=0, verbose_name='價格')),
                ('Stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('Image', models.ImageField(default='', upload_to='products/', verbose_name='商品圖片')),
                ('Color', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.colormodel', verbose_name='顏色')),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordersmodel')),
                ('Type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.producttypemodel', verbose_name='商品分類')),
                ('Size', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sizemodel', verbose_name='尺寸')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('ImageID', models.AutoField(primary_key=True, serialize=False, verbose_name='圖片ID')),
                ('ImageName', models.CharField(max_length=100, verbose_name='圖片名稱')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.products', verbose_name='商品')),
            ],
            options={
                'verbose_name': '圖片',
                'verbose_name_plural': '圖片',
            },
        ),
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('DescriptionID', models.AutoField(primary_key=True, serialize=False, verbose_name='敘述ID')),
                ('Description', models.TextField(verbose_name='敘述')),
                ('Product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='myapp.products', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品敘述',
                'verbose_name_plural': '商品敘述',
            },
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='customemail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.registered_user'),
        ),
    ]
