# Generated by Django 5.0.2 on 2024-03-05 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('total_views', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('daily_views', models.IntegerField(default=0)),
            ],
        ),
    ]
