# Generated by Django 5.0.2 on 2024-03-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(default='', max_length=100)),
                ('dcolor', models.CharField(default='', max_length=50)),
                ('dsize', models.CharField(default='', max_length=20)),
                ('dunitprice', models.IntegerField(default=0)),
                ('dquantity', models.IntegerField(default=0)),
                ('dtotal', models.IntegerField(default=0)),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordersmodel')),
            ],
        ),
    ]
