# Generated by Django 5.0.2 on 2024-03-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_detailmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='dorder',
        ),
        migrations.AlterField(
            model_name='detailmodel',
            name='dcolor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colormodel'),
        ),
        migrations.AlterField(
            model_name='detailmodel',
            name='dname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
        migrations.AlterField(
            model_name='detailmodel',
            name='dsize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sizemodel'),
        ),
        migrations.CreateModel(
            name='ProductColorSizeStockModel',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('Color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='myapp.colormodel', verbose_name='顏色ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='myapp.products', verbose_name='商品ID')),
                ('Size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='myapp.sizemodel', verbose_name='尺寸ID')),
            ],
        ),
    ]
