# Generated by Django 5.0.2 on 2024-03-05 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('ColorID', models.AutoField(primary_key=True, serialize=False, verbose_name='顏色ID')),
                ('ColorName', models.CharField(max_length=50, verbose_name='顏色名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('ProductName', models.CharField(default='', max_length=100, verbose_name='商品名稱')),
                ('Price', models.IntegerField(default=0, verbose_name='價格')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False, verbose_name='分類ID')),
                ('TypeName', models.CharField(max_length=50, verbose_name='分類名稱')),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('SizeID', models.AutoField(primary_key=True, serialize=False, verbose_name='尺寸ID')),
                ('SizeName', models.CharField(max_length=50, verbose_name='尺寸名稱')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grandtotal', models.IntegerField(default=0)),
                ('customname', models.CharField(default='', max_length=100)),
                ('customaddress', models.CharField(default='', max_length=100)),
                ('customphone', models.CharField(default='', max_length=100)),
                ('shipping_method', models.CharField(default='', max_length=50)),
                ('paytype', models.CharField(default='', max_length=50)),
                ('customemail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.registered_user')),
            ],
        ),
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(default='', max_length=100)),
                ('dcolor', models.CharField(default='', max_length=50)),
                ('dsize', models.CharField(default='', max_length=20)),
                ('dunitprice', models.IntegerField(default=0)),
                ('dquantity', models.IntegerField(default=0)),
                ('dtotal', models.IntegerField(default=0)),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ordersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('ImageID', models.AutoField(primary_key=True, serialize=False, verbose_name='圖片ID')),
                ('ImageName', models.CharField(max_length=100, verbose_name='圖片名稱')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.products', verbose_name='商品ID')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('DescriptionID', models.AutoField(primary_key=True, serialize=False, verbose_name='敘述ID')),
                ('Description', models.TextField(verbose_name='敘述')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='myapp.products', verbose_name='商品ID')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='Type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producttypemodel', verbose_name='分類ID'),
        ),
        migrations.CreateModel(
            name='ProductColorSizeStockModel',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('Color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='myapp.colormodel', verbose_name='顏色ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='myapp.products', verbose_name='商品ID')),
                ('Size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolorsizestocks', to='myapp.sizemodel', verbose_name='尺寸ID')),
            ],
        ),
    ]
