# Generated by Django 5.0.2 on 2024-03-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_colormodel_products_producttypemodel_sizemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='customemail',
        ),
        migrations.RemoveField(
            model_name='productcolorsizestockmodel',
            name='Color_id',
        ),
        migrations.RemoveField(
            model_name='productcolorsizestockmodel',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='productcolorsizestockmodel',
            name='Size_id',
        ),
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': '顏色', 'verbose_name_plural': '顏色'},
        ),
        migrations.AlterModelOptions(
            name='descriptionmodel',
            options={'verbose_name': '商品敘述', 'verbose_name_plural': '商品敘述'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': '圖片', 'verbose_name_plural': '圖片'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='producttypemodel',
            options={'verbose_name': '商品分類', 'verbose_name_plural': '商品分類'},
        ),
        migrations.AlterModelOptions(
            name='sizemodel',
            options={'verbose_name': '尺寸', 'verbose_name_plural': '尺寸'},
        ),
        migrations.RemoveField(
            model_name='descriptionmodel',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Type_id',
        ),
        migrations.AddField(
            model_name='descriptionmodel',
            name='Product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='myapp.products', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.products', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='products',
            name='Color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.colormodel', verbose_name='顏色'),
        ),
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(default='', upload_to='products/', verbose_name='商品圖片'),
        ),
        migrations.AddField(
            model_name='products',
            name='Size',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sizemodel', verbose_name='尺寸'),
        ),
        migrations.AddField(
            model_name='products',
            name='Stock',
            field=models.PositiveIntegerField(default=0, verbose_name='庫存'),
        ),
        migrations.AddField(
            model_name='products',
            name='Type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.producttypemodel', verbose_name='商品分類'),
        ),
        migrations.DeleteModel(
            name='DetailModel',
        ),
        migrations.DeleteModel(
            name='OrdersModel',
        ),
        migrations.DeleteModel(
            name='ProductColorSizeStockModel',
        ),
    ]
